USE SellingDatabase
GO
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bến Nghé',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bến Thành',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Cầu Kho',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Cầu Ông Lãnh',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Cô Giang',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Đa Kao',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Nguyễn Cư Trinh',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Nguyễn Thái Bình',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phạm Ngũ Lão',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Định',N'1',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Võ Thị Sáu',N'3',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'15',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'16',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'18',N'4',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'5',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'6',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Thuận',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Mỹ',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Thuận',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Hưng',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Kiểng',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Phong',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Phú',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Quy',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thuận Đông',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thuận Tây',N'7',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'15',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'16',N'8',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'15',N'10',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'15',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'16',N'11',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Phú Đông',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Đông Hưng Thuận',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hiệp Thành',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Chánh Hiệp',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Hưng Thuận',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thới Hiệp',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thới Nhất',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thạnh Lộc',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thạnh Xuân',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thới An',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Trung Mỹ Tây',N'12',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Phú Tây',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Chánh',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Hưng',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Lợi',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Đa Phước',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hưng Long',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Lê Minh Xuân',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phạm Văn Hai',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phong Phú',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Quy Đức',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Kiên',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Nhựt',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Quý Tây',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Túc',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Vĩnh Lộc A',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Vĩnh Lộc B',N'Bình Chánh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Lạc',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Lạc A',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Hưng Hòa',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Hưng Hoà A',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Hưng Hoà B',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Trị Đông',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Trị Đông A',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Trị Đông B',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Tạo',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Tạo A',N'Bình Tân',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'15',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'17',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'19',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'21',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'22',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'24',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'25',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'26',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'27',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'28',N'Bình Thạnh',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Thới Đông',N'Cần Giờ',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Khánh',N'Cần Giờ',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Cần Thạnh',N'Cần Giờ',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Long Hòa',N'Cần Giờ',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Lý Nhơn',N'Cần Giờ',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tam Thôn Hiệp',N'Cần Giờ',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thạnh An',N'Cần Giờ',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Nhơn Tây',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Phú',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Mỹ',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Củ Chi',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hòa Phú',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Nhuận Đức',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phạm Văn Cội',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Hòa Đông',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Mỹ Hưng',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phước Hiệp',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phước Thạnh',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phước Vĩnh An',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân An Hội',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Phú Trung',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thạnh Đông',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thạnh Tây',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thông Hội',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thái Mỹ',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Trung An',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Trung Lập Hạ',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Trung Lập Thượng',N'Củ Chi',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'15',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'16',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'17',N'Gò Vấp',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bà Điểm',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Đông Thạnh',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hóc Môn',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Nhị Bình',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Hiệp',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thới Nhì',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Xuân',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thới Tam Thôn',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Trung Chánh',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Xuân Thới Đông',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Xuân Thới Sơn',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Xuân Thới Thượng',N'Hóc Môn',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hiệp Phước',N'Nhà Bè',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Long Thới',N'Nhà Bè',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Nhà Bè',N'Nhà Bè',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Nhơn Đức',N'Nhà Bè',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Xuân',N'Nhà Bè',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phước Kiển',N'Nhà Bè',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phước Lộc',N'Nhà Bè',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'15',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'17',N'Phú Nhuận',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'1',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'2',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'3',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'4',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'5',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'6',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'7',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'8',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'9',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'10',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'11',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'12',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'13',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'14',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'15',N'Tân Bình',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hiệp Tân',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hòa Thạnh',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Thạnh',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Thọ Hòa',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Trung',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Sơn Kỳ',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Quý',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Sơn Nhì',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thành',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Thới Hòa',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tây Thạnh',N'Tân Phú',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Khánh',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Lợi Đông',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'An Phú',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Chiểu',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Thọ',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Trưng Đông',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Bình Trưng Tây',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Cát Lái',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hiệp Bình Chánh',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hiệp Bình Phước',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Hiệp Phú',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Linh Chiểu',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Linh Đông',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Linh Tây',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Linh Trung',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Linh Xuân',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Long Bình',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Long Phước',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Long Thạnh Mỹ',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Long Trường',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phú Hữu',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phước Bình',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phước Long A',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Phước Long B',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tam Bình',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tam Phú',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tân Phú',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tăng Nhơn Phú A',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Tăng Nhơn Phú B',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thạnh Mỹ Lợi',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thảo Điền',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Thủ Thiêm',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Trường Thạnh',N'Thủ Đức',N'TPHCM')
INSERT INTO Area (AreaWard, AreaDistrict, AreaCity) VALUES (N'Trường Thọ',N'Thủ Đức',N'TPHCM')

GO

SELECT * FROM dbo.Area go

INSERT INTO StatusCategory (StatusName) VALUES ('Error')
INSERT INTO StatusCategory (StatusName) VALUES ('Default')
INSERT INTO StatusCategory (StatusName) VALUES ('Success')
INSERT INTO StatusCategory (StatusName) VALUES ('Failed')
INSERT INTO StatusCategory (StatusName) VALUES ('Canceled')
INSERT INTO StatusCategory (StatusName) VALUES ('Waiting')
INSERT INTO StatusCategory (StatusName) VALUES ('Processing')
INSERT INTO StatusCategory (StatusName) VALUES ('Valid')

SELECT * FROM dbo.StatusCategory GO

DBCC CHECKIDENT ('[dbo].[ProductType]', RESEED, 0)
INSERT INTO ProductType (ProductTypeName) VALUES (N'Cơm')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Bún')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Bánh mì')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Thức ăn nhanh')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Món nướng')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Món chiên')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Món chay')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Trà sữa')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Cafe')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Sinh tố')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Đá xay')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Nước ép hoa quả')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Kem')
INSERT INTO ProductType (ProductTypeName) VALUES (N'Yogurt')
GO

SELECT * FROM dbo.ProductType GO


