/*
    MSSV: 20120138
    Họ và tên: Lê Thành Nam
*/


-- 1. Create users
-- a. Create users
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER JOHN IDENTIFIED BY JOHN;

GRANT CONNECT TO JOHN;

GRANT CREATE TABLE TO JOHN;

ALTER USER JOHN QUOTA 10M ON USERS;

/

CREATE USER JOE IDENTIFIED BY JOE;

GRANT CONNECT TO JOE;

GRANT CREATE TABLE TO JOE;

ALTER USER JOE QUOTA 10M ON USERS;

/

CREATE USER FRED IDENTIFIED BY FRED;

GRANT CONNECT TO FRED;

GRANT CREATE TABLE TO FRED;

ALTER USER FRED QUOTA 10M ON USERS;

/

CREATE USER LYNN IDENTIFIED BY LYNN;

GRANT CONNECT TO LYNN;

GRANT CREATE TABLE TO LYNN;

ALTER USER LYNN QUOTA 10M ON USERS;

/

CREATE USER AMY IDENTIFIED BY AMY;

GRANT CONNECT TO AMY;

GRANT CREATE TABLE TO AMY;

ALTER USER AMY QUOTA 10M ON USERS;

/

CREATE USER BETH IDENTIFIED BY BETH;

GRANT CONNECT TO BETH;

GRANT CREATE TABLE TO BETH;

ALTER USER BETH QUOTA 10M ON USERS;

/

-- b. Check quota
SELECT
    *
FROM
    DBA_TS_QUOTAS
WHERE
    TABLESPACE_NAME = 'USERS';

-- 2. Create Attendance table
CREATE TABLE ATTENDANCE(
    ID INT PRIMARY KEY,
    NAME NVARCHAR2(30)
);

-- a. Create Roles
CREATE ROLE DATAENTRY;

CREATE ROLE SUPERVISOR;

CREATE ROLE MANAGEMENT;

-- b. Grant roles to users

GRANT DATAENTRY TO JOHN, JOE, LYNN;

GRANT SUPERVISOR TO FRED;

GRANT MANAGEMENT TO AMY, BETH;

-- c. Grant privilege

GRANT SELECT, INSERT, UPDATE ON ATTENDANCE TO DATAENTRY;

GRANT SELECT, DELETE ON ATTENDANCE TO SUPERVISOR;

GRANT SELECT ON ATTENDANCE TO MANAGEMENT;

-- d. Check privileges were granted to roles
SELECT
    *
FROM
    DBA_TAB_PRIVS
WHERE
    GRANTEE = 'DATAENTRY';

SELECT
    *
FROM
    DBA_TAB_PRIVS
WHERE
    GRANTEE = 'SUPERVISOR';

SELECT
    *
FROM
    DBA_TAB_PRIVS
WHERE
    GRANTEE = 'MANAGEMENT';

SELECT
    *
FROM
    DBA_ROLE_PRIVS
WHERE
    GRANTED_ROLE = 'DATAENTRY';

SELECT
    *
FROM
    DBA_ROLE_PRIVS
WHERE
    GRANTED_ROLE = 'SUPERVISOR';

SELECT
    *
FROM
    DBA_ROLE_PRIVS
WHERE
    GRANTED_ROLE = 'MANAGEMENT';

SELECT
    *
FROM
    USER_TAB_PRIVS
WHERE
    TABLE_NAME = 'ATTENDANCE';

-- 3. Create a new user and grant UPDATE privilege to a user on a specific column
-- B1.Create a new user
CREATE USER NAMEMANAGER IDENTIFIED BY pc123;

GRANT CONNECT TO NAMEMANAGER;

-- B2. Grant UPDATE privilege to NAMEMANAGER on column NAME
GRANT UPDATE(NAME) ON ATTENDANCE TO NAMEMANAGER;

-- 4. Data Dictionary
-- a. Find privileges that have "CONTEXT" in their name
SELECT
    *
FROM
    DBA_SYS_PRIVS
WHERE
    PRIVILEGE LIKE '%CONTEXT%';

-- b. List all users who have been granted the SELECT ANY TABLE system privilege
SELECT
    GRANTEE
FROM
    DBA_SYS_PRIVS
WHERE
    PRIVILEGE = 'SELECT ANY TABLE';

-- 5.
-- a. Assign password to role DataEntry
ALTER USER JOHN IDENTIFIED BY MGT;

ALTER USER JOE IDENTIFIED BY MGT;

ALTER USER LYNN IDENTIFIED BY MGT;

-- b. Allow John grants privileges to other users
GRANT GRANT ANY PRIVILEGE TO JOHN WITH ADMIN OPTION;

-- c: Sau khi gán tất cả quyền mà user John có cho user Beth thì user Beth cũng có quyền INSERT, UPDATE trên bảng ATTENDANCE

/*
DROP USER JOHN CASCADE;
DROP USER AMY CASCADE;
DROP USER FRED CASCADE;
DROP USER BETH CASCADE;
DROP USER LYNN CASCADE;
DROP USER JOE CASCADE;
DROP USER NAMEMANAGER CASCADE;

DROP ROLE DataEntry;
DROP ROLE MANAGEMENT;
DROP ROLE Supervisor;
*/