-- Câu 1: Hiển thị tên nhân viên và thu nhập của nhân viên đó trong năm
CREATE OR REPLACE PROCEDURE SP_CAU1_THUNHAPNV_20120138(
    CURSOR_ OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN CURSOR_ FOR
        SELECT
            ENAME, SAL*12 + NVL(COMM, 0) AS THUNHAP
        FROM
            EMP_20120138;
    DBMS_SQL.RETURN_RESULT(CURSOR_);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No record found');
        CLOSE CURSOR_;
END;
/

VARIABLE CURSOR_ REFCURSOR;

EXECUTE SP_CAU1_THUNHAPNV_20120138(:CURSOR_);

-- Câu 2: Hiển thị cấu trúc bảng
CREATE OR REPLACE PROCEDURE SP_CAUTRUCBANGEMP_20120138
IS
    CURSOR1 SYS_REFCURSOR;
BEGIN
    OPEN CURSOR1 FOR
        SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, DATA_DEFAULT
        FROM ALL_TAB_COLUMNS 
        WHERE TABLE_NAME='EMP_20120138';
    DBMS_SQL.RETURN_RESULT(CURSOR1);

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No record found');
        CLOSE CURSOR1;
END;
/

EXECUTE SP_CAUTRUCBANGEMP_20120138;

-- Câu 3: Thay đổi nhãn và định dạng hiển thị của cột sal và hiredate trong bảng emp
CREATE OR REPLACE PROCEDURE SP_SALHIREDATE_20120138 IS
    CURSOR1 SYS_REFCURSOR;
BEGIN
    OPEN CURSOR1 FOR
        SELECT
            EMPNO, ENAME, JOB, MGR, TO_CHAR(HIREDATE, 'dd-mm-yyyy') AS HD, SAL AS SALARY, COMM, DEPTNO
        FROM
            EMP_20120138;
    DBMS_SQL.RETURN_RESULT(CURSOR1);

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No record found');
        CLOSE CURSOR1;
END;
/

EXECUTE SP_SALHIREDATE_20120138;

--drop procedure SP_SALHIREDATE_20120138; drop procedure SP_CAUTRUCBANGEMP_20120138; drop procedure SP_CAU1_THUNHAPNV_20120138;